# Generated by Django 3.1 on 2020-08-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
